name: Getting Started Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: 0-getting-started
        run: npm ci

      - name: Getting Started - Build and test ${{ matrix.node-version }}
        working-directory: 0-getting-started
      - run: npm run build --if-present
      - run: npm test
